import fs from 'node:fs';
import crypto from 'node:crypto';

const EXPECTED={artifactId:11051122672,artifactSHA256:'acd9dea52a01069790f6165a57753353bc45178d6a68a92d81bb1c9d338166e7',jsonSHA256:'4f239b3ac7df734d56f0be5dba70003bc7448948ad5adc83ade7bb3c6c913ad1',sourceCommit:'60b2fe0adefff620cf5865d5d6757c26d935bf0b'};
const BOOTSTRAP={bootstrapMethod:'paired bootstrap with replacement over paired state-level differences',bootstrapResamples:10000,bootstrapSeed:141405,confidenceLevel:0.95,intervalMethod:'percentile',quantileMethod:'linear interpolation, p=(n-1)q',resamplingUnit:'paired stateKey',statistic:'mean(leftMetric - rightMetric)',randomGenerator:'xorshift32; per-comparison deterministic sub-seed derived with FNV-1a from bootstrapSeed + comparison'};
const COMPARISONS=['A_REDLINE_vs_GUARD','B_REDLINE_vs_RAM','C_REDLINE_vs_GUARD','C_REDLINE_vs_RAM','C_GUARD_vs_RAM'];
const METRICS=['playerHPDelta','enemyHPDelta','survival'];
const sha256File=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function quantile(v,q){const a=[...v].sort((x,y)=>x-y),p=(a.length-1)*q,l=Math.floor(p),h=Math.ceil(p);return l===h?a[l]:a[l]+(a[h]-a[l])*(p-l)}
function fnv1a(s){let h=0x811c9dc5;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,0x01000193)}return h>>>0}
function xorshift32(seed){let x=seed>>>0;if(!x)x=0x9e3779b9;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function bootstrap(rows,label){const n=rows.length,rng=xorshift32(fnv1a(String(BOOTSTRAP.bootstrapSeed)+':'+label)),vals={playerHPDelta:new Array(n),enemyHPDelta:new Array(n),survival:new Array(n)};for(let i=0;i<n;i++){const r=rows[i];vals.playerHPDelta[i]=Number(r.left.playerHPDelta)-Number(r.right.playerHPDelta);vals.enemyHPDelta[i]=Number(r.left.enemyHPDelta)-Number(r.right.enemyHPDelta);vals.survival[i]=Number(!!r.left.survival)-Number(!!r.right.survival)}const estimates={};for(const m of METRICS)estimates[m]=vals[m].reduce((s,v)=>s+v,0)/n;const cis=Object.fromEntries(METRICS.map(m=>[m,new Array(BOOTSTRAP.bootstrapResamples)]));for(let b=0;b<BOOTSTRAP.bootstrapResamples;b++){const sums={playerHPDelta:0,enemyHPDelta:0,survival:0};for(let i=0;i<n;i++){const j=Math.floor(rng()*n);for(const m of METRICS)sums[m]+=vals[m][j]}for(const m of METRICS)cis[m][b]=sums[m]/n}const a=(1-BOOTSTRAP.confidenceLevel)/2;return Object.fromEntries(METRICS.map(m=>[m,{estimate:estimates[m],lower:quantile(cis[m],a),upper:quantile(cis[m],1-a)}]))}
function logGamma(z){const p=[676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-0.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<0.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z-=1;let x=0.9999999999998099;for(let i=0;i<p.length;i++)x+=p[i]/(z+i+1);const t=z+p.length-0.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x)}
function exactMcNemar(rows){let b=0,c=0;for(const r of rows){const l=!!r.left.survival,rr=!!r.right.survival;if(l&&!rr)b++;if(!l&&rr)c++}const n=b+c;if(!n)return{b,c,discordantPairs:0,exactTwoSidedP:1};const k=Math.min(b,c),log2=Math.log(2),logs=[];for(let i=0;i<=k;i++)logs.push(logGamma(n+1)-logGamma(i+1)-logGamma(n-i+1)-n*log2);const max=Math.max(...logs);let tail=0;for(const x of logs)tail+=Math.exp(x-max);tail*=Math.exp(max);return{b,c,discordantPairs:n,exactTwoSidedP:Math.min(1,2*tail)}}
function provenance(population,comparison,metric,N,estimate){return{artifactId:EXPECTED.artifactId,artifactSHA256:EXPECTED.artifactSHA256,jsonSHA256:EXPECTED.jsonSHA256,sourceCommit:EXPECTED.sourceCommit,analysisCommit:process.env.GITHUB_SHA||'LOCAL_UNSET',population,comparison,metric,N,statistic:BOOTSTRAP.statistic,bootstrapMethod:BOOTSTRAP.bootstrapMethod,bootstrapResamples:BOOTSTRAP.bootstrapResamples,bootstrapSeed:BOOTSTRAP.bootstrapSeed,intervalMethod:BOOTSTRAP.intervalMethod,confidenceLevel:BOOTSTRAP.confidenceLevel,softwareVersion:process.version,runtime:'Node.js '+process.version+' / GitHub Actions ubuntu-latest',timestamp:new Date().toISOString(),estimate}}
function main(input,outputJson,outputMd){const jsonSha=sha256File(input),source=JSON.parse(fs.readFileSync(input,'utf8'));if(jsonSha!==EXPECTED.jsonSHA256)throw new Error('JSON SHA256 mismatch: '+jsonSha);if(source.phase!=='14-B'||source.comparisons?.length!==14118)throw new Error('unexpected Phase 14-B artifact');
const report={phase:'14-E',classification:'RECONSTRUCTED_WITH_EXPLICIT_METHOD',historicalPhase14C:{status:'ORIGINAL BOOTSTRAP PROCEDURE NOT RECOVERABLE',historicalIntervals:'NOT AVAILABLE FOR EXACT HISTORICAL REPRODUCTION',note:'No Phase 14-C report, bootstrap metadata, or interval-generating procedure was found in the inspected repository/default-branch history. The authentic Phase 14-B artifact contains 14,118 paired comparison rows and no bootstrap metadata.'},bootstrapProvenance:{status:'RECONSTRUCTED_ANALYSIS',...BOOTSTRAP,softwareVersion:process.version,runtime:'Node.js '+process.version+' / GitHub Actions ubuntu-latest',sourceCommit:EXPECTED.sourceCommit,analysisCommit:process.env.GITHUB_SHA||'LOCAL_UNSET',artifactId:EXPECTED.artifactId,artifactSHA256:EXPECTED.artifactSHA256,jsonSHA256:jsonSha,timestamp:new Date().toISOString()},reportingCorrection:{branchLevelMetrics:['incomingDamage','affectedCardDamage','energyDelta','nitroDelta'],pairedDifferenceMetrics:['playerHPDelta','enemyHPDelta','survival'],correction:'incomingDamage is a branch-level metric and is not the paired playerHPDelta difference.'},comparisons:{},mcnemar:{},provenanceContract:{requiredFields:['artifactId','artifactSHA256','jsonSHA256','sourceCommit','analysisCommit','population','comparison','metric','N','statistic','bootstrapMethod','bootstrapResamples','bootstrapSeed','intervalMethod','confidenceLevel','softwareVersion','runtime','timestamp']},historicalArtifact:'UNCHANGED',gameplayDesignChanges:'NONE'};
for(const name of COMPARISONS){const rows=source.comparisons.filter(r=>name==='A_REDLINE_vs_GUARD'?r.population==='A':name==='B_REDLINE_vs_RAM'?r.population==='B':r.population==='C'&&r.comparison===name.replace(/^C_/,''));if(!rows.length)throw new Error('empty '+name);const results=bootstrap(rows,name);report.comparisons[name]={population:name[0],comparison:name,N:rows.length,metrics:{}};for(const m of METRICS){const ci=results[m];report.comparisons[name].metrics[m]={N:rows.length,statistic:BOOTSTRAP.statistic,estimate:ci.estimate,confidenceInterval:[ci.lower,ci.upper],historicalPhase14CValue:null,historicalComparisonStatus:'NOT_AVAILABLE',provenance:provenance(name[0],name,m,rows.length,ci.estimate)}}report.mcnemar[name]={statistic:'exact two-sided McNemar test on paired survival',...exactMcNemar(rows)}}
fs.writeFileSync(outputJson,JSON.stringify(report,null,2)+'\n');
const out=['# PHASE 14-E — RECONSTRUCTED EVIDENCE','','## Classification','','RECONSTRUCTED_WITH_EXPLICIT_METHOD','','## Historical Phase 14-C','','**ORIGINAL BOOTSTRAP PROCEDURE NOT RECOVERABLE**','','Historical Phase 14-C interval values are not available for exact historical reproduction and are not relabeled as reconstructed values.','','## Bootstrap provenance','', '- Method: '+BOOTSTRAP.bootstrapMethod,'- Resamples: '+BOOTSTRAP.bootstrapResamples,'- Seed: '+BOOTSTRAP.bootstrapSeed,'- Confidence level: '+BOOTSTRAP.confidenceLevel,'- Interval method: '+BOOTSTRAP.intervalMethod,'- Quantile method: '+BOOTSTRAP.quantileMethod,'- Resampling unit: '+BOOTSTRAP.resamplingUnit,'- Statistic: '+BOOTSTRAP.statistic,'- Random generator: '+BOOTSTRAP.randomGenerator,'- Runtime: Node.js '+process.version,'- Source commit: '+EXPECTED.sourceCommit,'- Analysis commit: '+(process.env.GITHUB_SHA||'LOCAL_UNSET'),'- Artifact ID: '+EXPECTED.artifactId,'- Artifact SHA256: '+EXPECTED.artifactSHA256,'- JSON SHA256: '+jsonSha,'','## Reporting correction','','- incomingDamage remains a branch-level metric and is not the paired playerHPDelta difference.','- playerHPDelta, enemyHPDelta, and survival are paired differences computed left minus right for the same stateKey.','- Historical artifact is unchanged.','','## Reconstructed intervals',''];
for(const [name,v] of Object.entries(report.comparisons)){out.push('### '+name,'','| Metric | N | Estimate | 95% CI |','|---|---:|---:|---:|');for(const [m,x] of Object.entries(v.metrics))out.push('| '+m+' | '+x.N+' | '+x.estimate+' | ['+x.confidenceInterval[0]+', '+x.confidenceInterval[1]+'] |');const mc=report.mcnemar[name];out.push('','McNemar exact two-sided: b='+mc.b+', c='+mc.c+', discordant='+mc.discordantPairs+', p='+mc.exactTwoSidedP,'')}
out.push('## Gate','','Historical artifact: UNCHANGED','','Gameplay/design changes: NONE','','Phase 14-E reconstructed analysis: COMPLETE','');fs.writeFileSync(outputMd,out.join('\n'))}
const [input,outputJson,outputMd]=process.argv.slice(2);if(!input||!outputJson||!outputMd)throw new Error('usage: node phase14e_reconstruct.mjs INPUT_JSON OUTPUT_JSON OUTPUT_MD');main(input,outputJson,outputMd);