import fs from 'node:fs';
import crypto from 'node:crypto';

const EXPECTED={artifactId:11051122672,artifactSHA256:'acd9dea52a01069790f6165a57753353bc45178d6a68a92d81bb1c9d338166e7',jsonSHA256:'4f239b3ac7df734d56f0be5dba70003bc7448948ad5adc83ade7bb3c6c913ad1',sourceCommit:'60b2fe0adefff620cf5865d5d6757c26d935bf0b'};
const BOOTSTRAP={bootstrapMethod:'paired bootstrap with replacement over paired state-level differences',bootstrapResamples:10000,bootstrapSeed:141405,confidenceLevel:0.95,intervalMethod:'percentile',quantileMethod:'linear interpolation, p=(n-1)q',resamplingUnit:'paired stateKey',statistic:'mean(leftMetric - rightMetric)'};
const COMPARISONS=['A_REDLINE_vs_GUARD','B_REDLINE_vs_RAM','C_REDLINE_vs_GUARD','C_REDLINE_vs_RAM','C_GUARD_vs_RAM'];
const METRICS=['playerHPDelta','enemyHPDelta','survival'];
const sha256File=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function quantile(v,q){const a=[...v].sort((x,y)=>x-y);if(!a.length)return null;const p=(a.length-1)*q,l=Math.floor(p),h=Math.ceil(p);return l===h?a[l]:a[l]+(a[h]-a[l])*(p-l);}
function fnv1a(s){let h=0x811c9dc5;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,0x01000193)}return h>>>0;}
function xorshift32(seed){let x=seed>>>0;if(!x)x=0x9e3779b9;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function bootstrap(values,label){const n=values.length,rng=xorshift32(fnv1a(String(BOOTSTRAP.bootstrapSeed)+':'+label)),reps=new Array(BOOTSTRAP.bootstrapResamples);for(let b=0;b<reps.length;b++){let sum=0;for(let i=0;i<n;i++)sum+=values[Math.floor(rng()*n)];reps[b]=sum/n}const a=1-BOOTSTRAP.confidenceLevel;return{estimate:values.reduce((s,v)=>s+v,0)/n,lower:quantile(reps,a/2),upper:quantile(reps,1-a/2)}}
function exactMcNemar(rows){let b=0,c=0;for(const r of rows){const l=!!r.left.survival,rr=!!r.right.survival;if(l&&!rr)b++;if(!l&&rr)c++}const n=b+c;if(!n)return{b,c,discordantPairs:0,exactTwoSidedP:1};const k=Math.min(b,c);let comb=1n,low=0n;for(let i=0;i<=k;i++){if(i)comb=comb*BigInt(n-i+1)/BigInt(i);low+=comb}const total=1n<<BigInt(n);let num=2n*low;if(num>total)num=total;return{b,c,discordantPairs:n,exactTwoSidedP:Number(num)/Number(total)}}
function values(rows,m){return rows.map(r=>{const l=m==='survival'?Number(!!r.left.survival):Number(r.left[m]);const rr=m==='survival'?Number(!!r.right.survival):Number(r.right[m]);return l-rr})}
function audit(rows){return{branchLevelMetrics:['incomingDamage','affectedCardDamage','energyDelta','nitroDelta'],pairedDifferenceMetrics:['playerHPDelta','enemyHPDelta','survival'],correction:'incomingDamage is a branch-level metric and is not the paired playerHPDelta difference.'}}
function main(input,outputJson,outputMd){const jsonSha=sha256File(input);if(jsonSha!==EXPECTED.jsonSHA256)throw new Error('JSON SHA256 mismatch: '+jsonSha);const source=JSON.parse(fs.readFileSync(input,'utf8'));if(source.phase!=='14-B'||source.comparisons?.length!==25353)throw new Error('unexpected Phase 14-B artifact');
const report={phase:'14-E',classification:'RECONSTRUCTED_WITH_EXPLICIT_METHOD',historicalPhase14C:{status:'NOT_RECOVERABLE_FROM_REPOSITORY_OR_PHASE14B_ARTIFACT',historicalIntervals:'NOT_RECONSTRUCTED_AS_HISTORICAL_VALUES',note:'No Phase 14-C report, bootstrap metadata, or interval-generating procedure was found in the inspected repository/default-branch history. The Phase 14-B artifact contains comparisons and descriptive summaries but no bootstrap metadata.'},bootstrapProvenance:{status:'NOT_RECOVERABLE',...BOOTSTRAP,softwareVersion:process.version,runtime:'Node.js '+process.version+' / GitHub Actions ubuntu-latest',sourceCommit:EXPECTED.sourceCommit,analysisCommit:process.env.GITHUB_SHA||'LOCAL_UNSET',artifactId:EXPECTED.artifactId,artifactSHA256:EXPECTED.artifactSHA256,jsonSHA256:jsonSha,timestamp:new Date().toISOString()},reportingCorrection:audit(source.comparisons),comparisons:{},mcnemar:{},provenanceContract:{requiredFields:['artifactId','artifactSHA256','jsonSHA256','sourceCommit','analysisCommit','population','comparison','metric','N','statistic','bootstrapMethod','bootstrapResamples','bootstrapSeed','intervalMethod','confidenceLevel','softwareVersion','runtime','timestamp']},historicalArtifact:'UNCHANGED',gameplayDesignChanges:'NONE'};
for(const name of COMPARISONS){const rows=source.comparisons.filter(r=>name==='A_REDLINE_vs_GUARD'?r.population==='A':name==='B_REDLINE_vs_RAM'?r.population==='B':r.population==='C'&&r.comparison===name.replace(/^C_/,''));if(!rows.length)throw new Error('empty '+name);report.comparisons[name]={population:name[0],comparison:name,N:rows.length,metrics:{}};for(const m of METRICS){const v=values(rows,m),ci=bootstrap(v,name+':'+m);report.comparisons[name].metrics[m]={N:v.length,statistic:'mean paired difference (left - right)',estimate:ci.estimate,confidenceInterval:[ci.lower,ci.upper],historicalPhase14CValue:null,historicalComparisonStatus:'NOT_AVAILABLE'}}report.mcnemar[name]={statistic:'exact two-sided McNemar test on paired survival',...exactMcNemar(rows)}}
fs.writeFileSync(outputJson,JSON.stringify(report,null,2)+'\n');
const out=['# PHASE 14-E — RECONSTRUCTED EVIDENCE','','## Classification','','RECONSTRUCTED_WITH_EXPLICIT_METHOD','','## Historical Phase 14-C','','Bootstrap provenance: NOT RECOVERABLE. Historical interval values are not relabeled as Phase 14-E values.','','## Bootstrap provenance','', '- Method: '+BOOTSTRAP.bootstrapMethod,'- Resamples: '+BOOTSTRAP.bootstrapResamples,'- Seed: '+BOOTSTRAP.bootstrapSeed,'- Confidence level: '+BOOTSTRAP.confidenceLevel,'- Interval method: '+BOOTSTRAP.intervalMethod,'- Quantile method: '+BOOTSTRAP.quantileMethod,'- Resampling unit: '+BOOTSTRAP.resamplingUnit,'- Statistic: '+BOOTSTRAP.statistic,'- Runtime: Node.js '+process.version,'- Source commit: '+EXPECTED.sourceCommit,'- Analysis commit: '+(process.env.GITHUB_SHA||'LOCAL_UNSET'),'- Artifact ID: '+EXPECTED.artifactId,'- Artifact SHA256: '+EXPECTED.artifactSHA256,'- JSON SHA256: '+jsonSha,'','## Reporting correction','','- incomingDamage remains a branch-level metric.','- playerHPDelta and enemyHPDelta paired differences are explicitly left minus right for the same stateKey.','- survival paired difference is Number(left.survival) minus Number(right.survival).','- Historical artifact is unchanged.','','## Reconstructed intervals',''];
for(const [name,v] of Object.entries(report.comparisons)){out.push('### '+name,'','| Metric | N | Estimate | 95% CI |','|---|---:|---:|---:|');for(const [m,x] of Object.entries(v.metrics))out.push('| '+m+' | '+x.N+' | '+x.estimate+' | ['+x.confidenceInterval[0]+', '+x.confidenceInterval[1]+'] |');const mc=report.mcnemar[name];out.push('','McNemar exact two-sided: b='+mc.b+', c='+mc.c+', discordant='+mc.discordantPairs+', p='+mc.exactTwoSidedP,'')}
out.push('## Gate','','Historical artifact: UNCHANGED','','Gameplay/design changes: NONE','','Phase 14-E reconstructed analysis: COMPLETE','');fs.writeFileSync(outputMd,out.join('\n'))}
const [input,outputJson,outputMd]=process.argv.slice(2);if(!input||!outputJson||!outputMd)throw new Error('usage: node phase14e_reconstruct.mjs INPUT_JSON OUTPUT_JSON OUTPUT_MD');main(input,outputJson,outputMd);