const CONFIG={simulations:10000,seedStart:100001,maxTurns:20,handSize:4,energyPerTurn:3,playerMaxHp:100,enemyMaxHp:150,enemyAttack:45,nitroGenerate:35,nitroSpendCost:40,redlineNitroCost:25,redlineDamageMultiplier:1.25,redlineIncomingMultiplier:1.25,varianceProfiles:{low:[.98,1.02],normal:[.9,1.1],high:[.75,1.25]}};
const CARDS={shot:{cost:1,damage:18},guard:{cost:1,block:14},pump:{cost:1,damage:7},ram:{cost:2,damage:26}};
const DECK=['shot','shot','guard','pump','ram','guard','ram']; const ENEMIES=['basic','reactive','pressure']; const POLICIES=['aggressive','defensive','generator','redline','adaptive']; const SEEDS=Array.from({length:10000},(_,i)=>100001+i);
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0, median=a=>{a=[...a].sort((a,b)=>a-b);return a[Math.floor(a.length/2)]||0}, pct=(n,d)=>d?n/d:0;
const rng=seed=>{let s=(seed>>>0)||0x6d2b79f5;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;s>>>=0;return s/4294967296}}; const shuffle=(a,r)=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function state(seed,model,enemyType='basic',variance='normal'){const r=rng(seed);return{seed,model,nitroOn:model!=='OFF',enemyType,variance,r,turn:1,hp:100,enemyHp:150,energy:3,block:0,nitro:0,enemyIntent:'ATTACK',redlinePending:false,delayed:null,hand:[],drawPile:shuffle(DECK,r),discard:[],actions:[],cardUses:{},energySpent:0,energyWaste:0,nitroGenerated:0,nitroSpent:0,redlineUses:0,redlineFailures:0,timingUses:0,enemyResponses:0,counterActions:0,deathCause:null};}
function draw(s,n){for(let i=0;i<n;i++){if(s.hand.length>=4)break;if(!s.drawPile.length){s.drawPile=shuffle(s.discard,s.r);s.discard=[]}const c=s.drawPile.shift();if(c)s.hand.push(c)}}
function intent(s){const x=s.r();if(s.enemyType==='reactive')s.enemyIntent=x<.45?'ATTACK':x<.75?'DEFEND':'SPECIAL';else if(s.enemyType==='pressure')s.enemyIntent=s.turn%3===0?'SPECIAL':x<.7?'ATTACK':'DEFEND';else s.enemyIntent=x<.7?'ATTACK':'DEFEND'}
function legal(s,id,cost=CARDS[id]?.cost){return !!CARDS[id]&&s.energy>=cost}
function score(s,id){if(!legal(s,id))return-Infinity; if(id==='shot')return 18+(s.enemyIntent==='DEFEND'?2:0); if(id==='guard')return s.enemyIntent==='ATTACK'?(s.hp<60?40:22):5; if(id==='pump')return s.nitro<50?15:2; if(id==='ram')return 26+(s.nitro>=40?14:0)+(s.enemyHp<=48?8:0)+(s.nitro<40?-3:0); return -Infinity}
function best(s){return s.hand.filter(id=>legal(s,id)).sort((a,b)=>score(s,b)-score(s,a))[0]||null}
function choose(s,p,model='A'){
 const l=s.hand.filter(id=>legal(s,id)); if(!l.length)return null;
 if(p==='defensive'&&s.enemyIntent==='ATTACK'&&l.includes('guard'))return{id:'guard',kind:'card'};
 if(p==='generator'&&l.includes('pump')&&s.nitro<55)return{id:'pump',kind:'card'};
 if(p==='redline'&&(model!=='C'&&model!=='NO_REDLINE'&&model!=='D_NO_REDLINE')&&s.nitro>=25&&s.enemyIntent!=='ATTACK')return{id:best(s),kind:'redline'};
 if(p==='adaptive'){
   if(s.enemyIntent==='ATTACK'&&s.hp<55&&l.includes('guard'))return{id:'guard',kind:'card'};
   if(s.nitro<35&&s.enemyIntent!=='ATTACK'&&l.includes('pump'))return{id:'pump',kind:'card'};
   if(s.nitro>=40&&l.includes('ram')&&(s.enemyHp<=55||s.energy>=2))return{id:'ram',kind:'card'};
   if(model!=='C'&&model!=='NO_REDLINE'&&model!=='D_NO_REDLINE'&&s.nitro>=25&&s.enemyIntent==='DEFEND'&&s.hp>55)return{id:best(s),kind:'redline'};
 }
 return{id:best(s),kind:'card'};
}
function damage(s,d){if(d<=0)return;const v=CONFIG.varianceProfiles[s.variance];d=Math.max(0,Math.round(d*(v[0]+(v[1]-v[0])*s.r())));s.enemyHp=Math.max(0,s.enemyHp-d)}
function play(s,id,opts={}){const d=CARDS[id];if(!d)return false;const cost=opts.cost??d.cost;if(s.energy<cost)return false;s.energy-=cost;s.energySpent+=cost;const i=s.hand.indexOf(id);if(i>=0){s.hand.splice(i,1);s.discard.push(id)}s.cardUses[id]=(s.cardUses[id]||0)+1;let dmg=d.damage;if(id==='guard'){s.block+=d.block;dmg=0}if(id==='pump'&&s.nitroOn){s.nitro=Math.min(100,s.nitro+35);s.nitroGenerated+=35}if(id==='ram'&&opts.ramSpend&&s.nitroOn){s.nitro-=40;s.nitroSpent+=40;dmg+=14}if(opts.redline){dmg=Math.round(dmg*1.25);s.actions.push('REDLINE+'+id)}else if(opts.ramSpend&&id==='ram')s.actions.push('NITRO+ram');else s.actions.push(id);if(dmg)damage(s,dmg);if(s.enemyType==='reactive'&&id==='shot'&&s.enemyIntent==='DEFEND'){s.enemyResponses++;s.enemyHp=Math.min(150,s.enemyHp+4)}if(s.enemyType==='reactive'&&id==='ram'&&s.enemyIntent==='SPECIAL'){s.enemyResponses++;s.counterActions++;s.hp=Math.max(0,s.hp-5)}return true}
function resolve(s,a){if(!a)return false;
  if(a.kind==='redline'){if(s.nitro<25)return false;s.nitro-=25;s.nitroSpent+=25;s.redlineUses++;s.redlinePending=true;return play(s,a.id,{redline:true})}
  if(a.kind==='guardNitro'){if(s.nitro<25||!legal(s,'guard'))return false;s.nitro-=25;s.nitroSpent+=25;s.timingUses++;s.actions.push('NITRO+guard');return play(s,'guard')}
  if(a.kind==='timing'){if(s.nitro<25||!legal(s,a.id))return false;s.energy-=CARDS[a.id].cost;s.energySpent+=CARDS[a.id].cost;s.nitro-=25;s.nitroSpent+=25;s.timingUses++;s.delayed=a.id;s.actions.push('TIMING+ARM:'+a.id);const i=s.hand.indexOf(a.id);if(i>=0){s.hand.splice(i,1);s.discard.push(a.id)}s.cardUses[a.id]=(s.cardUses[a.id]||0)+1;return true}
  return play(s,a.id,{ramSpend:a.ramSpend});
}
function enemy(s){let d=s.enemyIntent==='ATTACK'?45:s.enemyIntent==='SPECIAL'?18:0;if(s.redlinePending){d=Math.round(d*1.25);s.redlinePending=false}const b=Math.min(s.block,d);s.block-=b;d-=b;s.hp=Math.max(0,s.hp-d);if(s.hp<=0)s.deathCause=s.enemyIntent==='SPECIAL'?'ENEMY_SPECIAL':'ENEMY_ATTACK';
  if(s.delayed){const id=s.delayed;s.delayed=null;if(id==='guard')s.block+=14;else if(id==='shot')damage(s,18);else if(id==='pump'&&s.nitroOn){s.nitro=Math.min(100,s.nitro+35);s.nitroGenerated+=35}else if(id==='ram')damage(s,26);s.actions.push('TIMING+RESOLVE:'+id);
  }}
function run(seed,model='A',policy='adaptive',enemyType='basic',variance='normal'){const s=state(seed,model,enemyType,variance);draw(s,4);while(s.turn<=20&&s.hp>0&&s.enemyHp>0){s.energy=3;s.block=0;intent(s);let n=0;while(s.energy>0&&s.hp>0&&s.enemyHp>0&&n<3){let a=choose(s,policy,model);if(model==='B'&&s.nitro>=25&&s.enemyIntent==='ATTACK'&&s.hand.includes('guard')&&s.hp<70&&policy!=='generator')a={kind:'guardNitro',id:'guard'};if(model==='C'&&s.nitro>=25&&s.enemyIntent!=='ATTACK'&&s.hand.includes('shot')&&s.enemyHp>70&&policy!=='defensive')a={kind:'timing',id:'shot'};if(!a)break;if(a.id==='ram'&&s.nitro>=40&&model!=='D'&&model!=='D_NO_REDLINE')a={...a,ramSpend:true};const ok=resolve(s,a);n++;if(!ok||s.enemyHp<=0||s.hp<=0)break}s.energyWaste+=s.energy;if(s.enemyHp>0&&s.hp>0)enemy(s);draw(s,2);s.turn++}return{seed,model,win:s.enemyHp<=0&&s.hp>0,turns:Math.min(s.turn,20),energySpent:s.energySpent,energyWaste:s.energyWaste,nitroGenerated:s.nitroGenerated,nitroSpent:s.nitroSpent,nitroRemaining:s.nitro,nitroSpendFrequency:s.nitroSpent>0?1:0,timingUses:s.timingUses,redlineUses:s.redlineUses,cardUses:s.cardUses,actions:s.actions,deathCause:s.deathCause};}
function aggregate(rs){const uses={};for(const r of rs)for(const[k,v]of Object.entries(r.cardUses))uses[k]=(uses[k]||0)+v;const total=Object.values(uses).reduce((a,b)=>a+b,0);return{simulations:rs.length,winRate:pct(rs.filter(x=>x.win).length,rs.length),avgTurns:mean(rs.map(x=>x.turns)),medianTurns:median(rs.map(x=>x.turns)),energySpent:mean(rs.map(x=>x.energySpent)),energyWaste:mean(rs.map(x=>x.energyWaste)),nitroGenerated:mean(rs.map(x=>x.nitroGenerated)),nitroSpent:mean(rs.map(x=>x.nitroSpent)),nitroSpendFrequency:pct(rs.filter(x=>x.nitroSpent>0).length,rs.length),cardUsage:uses,cardUsageShare:Object.fromEntries(Object.entries(uses).map(([k,v])=>[k,pct(v,total)])),deathCauses:rs.reduce((m,r)=>{if(r.deathCause)m[r.deathCause]=(m[r.deathCause]||0)+1;return m},{})};}
function spenderStats(rs){const c={ram:0,guard:0,redline:0,timing:0};for(const r of rs)for(const a of r.actions){if(a==='NITRO+ram')c.ram++;if(a==='NITRO+guard')c.guard++;if(a.startsWith('REDLINE+'))c.redline++;if(a.startsWith('TIMING+ARM'))c.timing++;}const total=Object.values(c).reduce((a,b)=>a+b,0);const vals=Object.values(c).sort((a,b)=>b-a);return{counts:c,shares:Object.fromEntries(Object.entries(c).map(([k,v])=>[k,pct(v,total)])),mainSpenderShare:total?vals[0]/total:0,topTwoShare:total?(vals[0]+(vals[1]||0))/total:0};}
function pairedModel(seed,model,policy='adaptive'){const off=run(seed,'OFF',policy,'basic'),on=run(seed,model,policy,'basic');const n=Math.max(off.actions.length,on.actions.length);let d=0,t=0;for(let i=0;i<n;i++)if(off.actions[i]!==on.actions[i])d++;for(let i=0;i<n;i++)if((off.actions[i]||'').startsWith('TIMING')!== (on.actions[i]||'').startsWith('TIMING'))t++;return{seed,actionDiverged:d>0,timingDiverged:t>0,actionDivergenceCount:d,timingDivergenceCount:t,outcomeDiverged:off.win!==on.win}}
function policyResults(model){const o={};for(const p of POLICIES)o[p]=aggregate(SEEDS.map(s=>run(s,model,p)));return o}
function counterfactuals(){const states=[{id:1,hp:85,enemyHp:90,nitro:10,intent:'ATTACK'},{id:2,hp:35,enemyHp:90,nitro:80,intent:'ATTACK'},{id:3,hp:60,enemyHp:45,nitro:80,intent:'DEFEND'},{id:4,hp:60,enemyHp:140,nitro:50,intent:'SPECIAL'}];const chooseState=(s,model,nitroOn)=>{const x={...s,model,nitro:nitroOn?s.nitro:0,energy:3,hand:['shot','guard','pump','ram']};if(model==='B'&&nitroOn&&x.nitro>=25&&x.intent==='ATTACK'&&x.hp<70)return'guard (Nitro spend)';if(model==='C'&&nitroOn&&x.nitro>=25&&x.intent!=='ATTACK'&&x.enemyHp>70)return'shot (Nitro timing: defer)';if(model==='D'&&nitroOn&&x.nitro>=25&&x.intent==='DEFEND'&&x.hp>55)return'Redline + '+best(x);if(x.intent==='ATTACK'&&x.hp<55)return'guard';if(nitroOn&&x.nitro>=40&&x.enemyHp<=55)return'ram (Nitro spend)';return best(x)};return states.map(s=>({state:s,control:chooseState(s,'A',false),nitroA:chooseState(s,'A',true),modelB:chooseState(s,'B',true),modelC:chooseState(s,'C',true),modelD:chooseState(s,'D',true)}));}
function runExperiment(){const control=aggregate(SEEDS.map(s=>run(s,'A')));const controlExpected={winRate:.5531,avgTurns:5.3878,energyWaste:.3213,nitroGenerated:32.8195,nitroSpent:15.181};const phase4ControlArm={winRate:.5583,avgTurns:5.4129,energyWaste:.3617};const controlPass=Math.abs(control.winRate-controlExpected.winRate)<1e-12&&Math.abs(control.avgTurns-controlExpected.avgTurns)<1e-12&&Math.abs(control.energyWaste-controlExpected.energyWaste)<1e-12&&Math.abs(control.nitroGenerated-controlExpected.nitroGenerated)<1e-12&&Math.abs(control.nitroSpent-controlExpected.nitroSpent)<1e-12;const models={A:aggregate(SEEDS.map(s=>run(s,'A'))),B:aggregate(SEEDS.map(s=>run(s,'B')),),C:aggregate(SEEDS.map(s=>run(s,'C')),),D:aggregate(SEEDS.map(s=>run(s,'D'))),D_noRedline:aggregate(SEEDS.map(s=>run(s,'D_NO_REDLINE'))),noRedline:aggregate(SEEDS.map(s=>run(s,'NO_REDLINE')))};const spenders={A:spenderStats(SEEDS.map(s=>run(s,'A'))),B:spenderStats(SEEDS.map(s=>run(s,'B'))),C:spenderStats(SEEDS.map(s=>run(s,'C'))),D:spenderStats(SEEDS.map(s=>run(s,'D')))};const divergence={};for(const m of ['B','C','D']){const ps=SEEDS.map(s=>pairedModel(s,m));divergence[m]={actionDivergenceRate:pct(ps.filter(x=>x.actionDiverged).length,ps.length),timingDivergenceRate:pct(ps.filter(x=>x.timingDiverged).length,ps.length),outcomeDivergenceRate:pct(ps.filter(x=>x.outcomeDiverged).length,ps.length),avgActionDivergence:mean(ps.map(x=>x.actionDivergenceCount)),avgTimingDivergence:mean(ps.map(x=>x.timingDivergenceCount))};}const policy={};for(const m of ['A','B','C','D'])policy[m]=policyResults(m);const dom={};for(const m of ['A','B','C','D']){const vals=Object.values(policy[m]).map(x=>x.winRate);dom[m]=Math.max(...vals)-Math.min(...vals);}const cf=counterfactuals();const det=JSON.stringify(SEEDS.slice(0,250).map(s=>run(s,'B')))==JSON.stringify(SEEDS.slice(0,250).map(s=>run(s,'B')))&&JSON.stringify(SEEDS.slice(0,250).map(s=>run(s,'C')))==JSON.stringify(SEEDS.slice(0,250).map(s=>run(s,'C')));return{config:CONFIG,seeds:{start:100001,end:110000,count:10000},control:{reproducesPhase4NitroArm:controlPass,observed:control,expected:controlExpected,phase4ControlArmExpected:phase4ControlArm},models,spenders,divergence,policyWinRates:policy,dominanceSpread:dom,counterfactuals:cf,determinism:det,constantVariables:['card pool','deck','enemy pool','enemy intents','enemy behavior','policies','RNG','energy','damage variance','max turns','seed set'],modelDefinitions:{A:'Phase 4 control: Nitro -> Ram + Redline.',B:'Second spender: Guard may spend 25 Nitro for its existing 14 block; Ram remains 40-Nitro damage spender.',C:'Timing: spend 25 Nitro to arm an existing Shot for resolution after the enemy phase; energy cost remains 1 and no new resource is introduced.',D:'Redline isolated: Nitro may be spent only through Redline; Ram does not consume Nitro in this model.'}};}
console.log(JSON.stringify(runExperiment(),null,2));