import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { runExperiment } from '../rocket_bunny_phase14a/phase14a_causal_harness.mjs';

export const BASE_SHA='328cbb112bc806abe1ea43339129b650a7d7e53a';
export const PHASE14A_EXECUTED_SHA='605e9114e246116674749f42e1b6f3c546c36d59';
export const SEED_START=100001,SEED_END=110000;
export const EXPECTED={A:9548,B:1687,C:961,UNION:10274,EXCLUDED:1897};
export const EXPECTED_BRANCHES={A:19096,B:3374,C:2883,TOTAL:25353};
const METRICS=['affectedCardDamage','incomingDamage','playerHPDelta','enemyHPDelta','energyDelta','nitroDelta','survival','resourcesSpent.energy','resourcesSpent.nitro','resourcesRemaining.energy','resourcesRemaining.nitro','timing.enemyResolutionOccurred'];
function value(row,key){return key.split('.').reduce((v,k)=>v?.[k],row);}
function quantile(values,q){if(!values.length)return null;const a=[...values].sort((x,y)=>x-y),p=(a.length-1)*q,l=Math.floor(p),h=Math.ceil(p);return l===h?a[l]:a[l]+(a[h]-a[l])*(p-l);}
function stats(values){const n=values.length,nums=values.filter(v=>typeof v==='number').map(Number);if(!nums.length)return{n,numericN:0};const mean=nums.reduce((s,v)=>s+v,0)/nums.length;return{n,numericN:nums.length,mean,median:quantile(nums,.5),min:Math.min(...nums),max:Math.max(...nums),p10:quantile(nums,.1),p25:quantile(nums,.25),p75:quantile(nums,.75),p90:quantile(nums,.9),p95:quantile(nums,.95),p99:quantile(nums,.99)};}
function pairedDiff(left,right,metric){const out=[];for(let i=0;i<left.length;i++){const a=value(left[i],metric),b=value(right[i],metric);if(typeof a==='number'&&typeof b==='number')out.push(a-b);else if(typeof a==='boolean'&&typeof b==='boolean')out.push(Number(a)-Number(b));}return stats(out);}
function validate(result){assert.deepEqual(result.populations,{A:EXPECTED.A,B:EXPECTED.B,C:EXPECTED.C,UNION:EXPECTED.UNION});assert.equal(result.redlineEligibleWithoutGuardOrRam,EXPECTED.EXCLUDED);assert.equal(result.syntheticStates,0);assert.equal(result.deterministicReplay?.pass,true);assert.equal(result.comparisons.length,25353);const counts={A:0,B:0,C_REDLINE_vs_GUARD:0,C_REDLINE_vs_RAM:0,C_GUARD_vs_RAM:0};const states=new Set(),cStates=new Set();for(const r of result.comparisons){assert.equal(typeof r.stateKey,'string');assert.ok(r.left&&r.right);states.add(r.stateKey);if(r.population==='A')counts.A++;if(r.population==='B')counts.B++;if(r.population==='C'){cStates.add(r.stateKey);counts['C_'+r.comparison]++;}}assert.deepEqual(counts,{A:9548,B:1687,C_REDLINE_vs_GUARD:961,C_REDLINE_vs_RAM:961,C_GUARD_vs_RAM:961});assert.equal(states.size,10274);assert.equal(cStates.size,961);for(const key of cStates){const rows=result.comparisons.filter(r=>r.population==='C'&&r.stateKey===key);assert.equal(rows.length,3);assert.deepEqual(new Set(rows.map(r=>r.comparison)),new Set(['REDLINE_vs_GUARD','REDLINE_vs_RAM','GUARD_vs_RAM']));}return{counts,uniqueInputStates:states.size,cStates:cStates.size};}
function summaries(comparisons){const groups=new Map([['A_REDLINE_vs_GUARD',comparisons.filter(r=>r.population==='A')],['B_REDLINE_vs_RAM',comparisons.filter(r=>r.population==='B')],['C_REDLINE_vs_GUARD',comparisons.filter(r=>r.population==='C'&&r.comparison==='REDLINE_vs_GUARD')],['C_REDLINE_vs_RAM',comparisons.filter(r=>r.population==='C'&&r.comparison==='REDLINE_vs_RAM')],['C_GUARD_vs_RAM',comparisons.filter(r=>r.population==='C'&&r.comparison==='GUARD_vs_RAM')]]),out={};for(const[name,rows]of groups){const left=rows.map(r=>r.left),right=rows.map(r=>r.right);out[name]={N:rows.length,pairedStateKeys:new Set(rows.map(r=>r.stateKey)).size,leftAction:left[0]?.action??null,rightAction:right[0]?.action??null,divergence:{actionDivergence:rows.filter(r=>r.divergence.actionDivergence).length,timingDivergence:rows.filter(r=>r.divergence.timingDivergence).length,outcomeDivergence:rows.filter(r=>r.divergence.outcomeDivergence).length},metrics:{}};for(const m of METRICS)out[name].metrics[m]={left:stats(left.map(r=>value(r,m))),right:stats(right.map(r=>value(r,m))),pairedDifferenceLeftMinusRight:pairedDiff(left,right,m)};}return out;}
export function runPhase14B(){const r=runExperiment(),pairing=validate(r);return{phase:'14-B',status:'EXECUTED',baseSha:BASE_SHA,phase14aExecutedSha:PHASE14A_EXECUTED_SHA,runtime:{phase6:'328cbb112bc806abe1ea43339129b650a7d7e53a',phase9:'3f11f12d16ad0e4ec7228f5295b029d464658be4'},seeds:{start:SEED_START,end:SEED_END,count:10000},inputPopulation:{A:9548,B:1687,C:961,AOnly:8587,BOnly:726,UNION:10274,EXCLUDED:1897},branchCounts:{A_REDLINE:9548,A_GUARD:9548,B_REDLINE:1687,B_RAM:1687,C_REDLINE:961,C_GUARD:961,C_RAM:961,total:25353},pairingValidation:pairing,deterministicReplay:r.deterministicReplay,syntheticStates:0,noSpenderControl:r.noSpenderControl,rejectedStateAccounting:r.rejectedStateAccounting,summaries:summaries(r.comparisons),comparisons:r.comparisons,causalInterpretation:{observed:'Each comparison is a paired intervention from the same natural frozen state.',demonstrated:'The artifact records reproducible branch-level counterfactual execution under the historical runtime.',notDemonstrated:'No mechanic is selected, ranked, or declared globally superior.'}};}
if(process.argv[1]&&path.resolve(process.argv[1])===path.resolve(fileURLToPath(import.meta.url))){const out=process.argv[2]||'research-results/rocket-bunny-phase14b.json';fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,JSON.stringify(runPhase14B(),null,2)+'\n');console.log(out);}
