import assert from 'node:assert/strict';
import { runPhase8, runTests, replay, counterfactuals } from './phase8_redline_opportunity.mjs';
const x = runPhase8();
assert.equal(x.seeds.count, 10000);
assert.equal(x.simulations.A, 10000);
assert.equal(x.simulations.B, 10000);
assert.equal(x.simulations.total, 20000);
assert.equal(x.reproduction.A.nitroSpent, 18.6865);
assert.equal(x.reproduction.B.nitroSpent, 20.499);
assert.equal(x.opportunity.opportunities, 12949);
assert.equal(x.opportunity.activations, 4342);
assert.equal(x.opportunity.bothAvailable, 584);
assert.equal(x.allocation.A.ram, 53040);
assert.equal(x.allocation.A.guard, 133825);
assert.equal(x.allocation.B.ram, 48040);
assert.equal(x.allocation.B.guard, 48400);
assert.equal(x.allocation.B.redline, 108550);
assert.equal(x.determinism.A, true);
assert.equal(x.determinism.B, true);
assert.equal(x.tests, 'PASS');
assert.equal(counterfactuals().length, 4);
assert.equal(runTests(), 'PASS');
assert.equal(replay(250, 'A'), true);
assert.equal(replay(250, 'B'), true);
console.log('phase8_redline_opportunity.test.mjs: PASS');
