import fs from 'node:fs';
export const CONFIG=Object.freeze({simulations:10000,seedStart:100001,maxTurns:20,handSize:4,energyPerTurn:3,playerMaxHp:100,enemyMaxHp:150,enemyAttack:45,nitroGenerate:35,nitroSpendCost:40,nitroSpendBonus:14,redlineNitroCost:25,redlineDamageMultiplier:1.25,redlineIncomingMultiplier:1.25,varianceProfiles:{low:[.98,1.02],normal:[.9,1.1],high:[.75,1.25]}});
export const CARDS=Object.freeze({shot:{name:'DISPARO NEON',cost:1,damage:18},guard:{name:'ESCUDO DARK',cost:1,block:14},pump:{name:'NITRO PUMP',cost:1,damage:7},ram:{name:'EMBESTIDA NITRO',cost:2,damage:26}});
export const DECK=Object.freeze(['shot','shot','guard','pump','ram','guard','ram']);
export const ENEMIES=Object.freeze(['basic','reactive','pressure']);
export const POLICIES=Object.freeze(['aggressive','defensive','generator','redline','adaptive']);
export const SEEDS=Object.freeze(Array.from({length:CONFIG.simulations},(_,i)=>CONFIG.seedStart+i));
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const median=a=>{a=[...a].sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:0};
const pct=(n,d)=>d?n/d:0;
const rng=seed=>{let s=(seed>>>0)||0x6d2b79f5;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;s>>>=0;return s/4294967296}};
const shuffle=(a,r)=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};

export function makeState(seed,nitroOn,enemyType='basic',varianceProfile='normal'){const r=rng(seed);return{seed,nitroOn,enemyType,varianceProfile,r,turn:1,hp:100,enemyHp:150,energy:3,block:0,nitro:0,enemyIntent:'ATTACK',redlinePending:false,hand:[],drawPile:shuffle(DECK,r),discard:[],actions:[],cardUses:{},energySpent:0,energyWaste:0,nitroGenerated:0,nitroSpent:0,redlineUses:0,redlineFailures:0,enemyResponses:0,counterActions:0,deathCause:null,trace:[]}};
function draw(s,n){for(let i=0;i<n;i++){if(s.hand.length>=4)break;if(!s.drawPile.length){s.drawPile=shuffle(s.discard,s.r);s.discard=[]}const c=s.drawPile.shift();if(c)s.hand.push(c)}}
function intent(s){const x=s.r();if(s.enemyType==='reactive')s.enemyIntent=x<.45?'ATTACK':x<.75?'DEFEND':'SPECIAL';else if(s.enemyType==='pressure')s.enemyIntent=s.turn%3===0?'SPECIAL':x<.7?'ATTACK':'DEFEND';else s.enemyIntent=x<.7?'ATTACK':'DEFEND'}
const legal=(s,id)=>!!CARDS[id]&&s.energy>=CARDS[id].cost;
export function cardScore(s,id){if(!legal(s,id))return-Infinity;if(id==='shot')return 18+(s.enemyIntent==='DEFEND'?2:0);if(id==='guard')return s.enemyIntent==='ATTACK'?(s.hp<60?40:22):5;if(id==='pump')return s.nitroOn?((s.nitro<50?15:2)+(s.enemyIntent==='ATTACK'&&s.hp<60?-8:0)):7;if(id==='ram')return 26+(s.nitroOn&&s.nitro>=40?14:0)+(s.enemyHp<=48?8:0)+(s.nitroOn&&s.nitro<40?-3:0);return-Infinity}
const best=s=>s.hand.filter(id=>legal(s,id)).sort((a,b)=>cardScore(s,b)-cardScore(s,a))[0]||null;
export function choose(s,p){const l=s.hand.filter(id=>legal(s,id));if(!l.length)return null;if(p==='defensive'&&s.enemyIntent==='ATTACK'&&l.includes('guard'))return{kind:'card',id:'guard'};if(p==='generator'&&l.includes('pump')&&(!s.nitroOn||s.nitro<55))return{kind:'card',id:'pump'};if(p==='redline'&&s.nitroOn&&s.nitro>=25&&s.enemyIntent!=='ATTACK')return{kind:'redline',id:best(s)};if(p==='adaptive'){if(s.enemyIntent==='ATTACK'&&s.hp<55&&l.includes('guard'))return{kind:'card',id:'guard'};if(s.nitroOn&&s.nitro<35&&s.enemyIntent!=='ATTACK'&&l.includes('pump'))return{kind:'card',id:'pump'};if(s.nitroOn&&s.nitro>=40&&l.includes('ram')&&(s.enemyHp<=55||s.energy>=2))return{kind:'card',id:'ram'};if(s.nitroOn&&s.nitro>=25&&s.enemyIntent==='DEFEND'&&s.hp>55)return{kind:'redline',id:best(s)}}return{kind:'card',id:best(s)}}

function card(s,id,redline=false){const d=CARDS[id];if(!d||!legal(s,id))return false;s.energy-=d.cost;s.energySpent+=d.cost;const i=s.hand.indexOf(id);if(i>=0){s.hand.splice(i,1);s.discard.push(id)}s.cardUses[id]=(s.cardUses[id]||0)+1;let dmg=d.damage;if(id==='guard'){s.block+=14;dmg=0}if(id==='pump'&&s.nitroOn){s.nitro=Math.min(100,s.nitro+35);s.nitroGenerated+=35}if(id==='ram'&&s.nitroOn&&s.nitro>=40){s.nitro-=40;s.nitroSpent+=40;dmg+=14}if(redline){dmg=Math.round(dmg*1.25);s.actions.push('REDLINE+'+id)}else s.actions.push(id);if(dmg>0){const v=CONFIG.varianceProfiles[s.varianceProfile];dmg=Math.max(0,Math.round(dmg*(v[0]+(v[1]-v[0])*s.r())));s.enemyHp=Math.max(0,s.enemyHp-dmg)}if(s.enemyType==='reactive'&&id==='shot'&&s.enemyIntent==='DEFEND'){s.enemyResponses++;s.enemyHp=Math.min(150,s.enemyHp+4)}if(s.enemyType==='reactive'&&id==='ram'&&s.enemyIntent==='SPECIAL'){s.enemyResponses++;s.counterActions++;s.hp=Math.max(0,s.hp-5)}return true}
function resolve(s,a){if(!a)return false;if(a.kind==='redline'){if(!s.nitroOn||s.nitro<25){s.redlineFailures++;return false}s.nitro-=25;s.nitroSpent+=25;s.redlineUses++;s.redlinePending=true;return card(s,a.id,true)}return card(s,a.id)}
function enemy(s){let d=s.enemyIntent==='ATTACK'?45:s.enemyIntent==='SPECIAL'?18:0;if(s.nitroOn&&s.redlinePending){d=Math.round(d*1.25);s.redlinePending=false}const b=Math.min(s.block,d);s.block-=b;d-=b;s.hp=Math.max(0,s.hp-d);if(s.hp<=0)s.deathCause=s.enemyIntent==='SPECIAL'?'ENEMY_SPECIAL':'ENEMY_ATTACK'}

export function run(seed,nitroOn,policy='adaptive',enemyType='basic',trace=false,varianceProfile='normal'){const s=makeState(seed,nitroOn,enemyType,varianceProfile);draw(s,4);while(s.turn<=20&&s.hp>0&&s.enemyHp>0){s.energy=3;s.block=0;intent(s);let n=0;while(s.energy>0&&s.hp>0&&s.enemyHp>0&&n<3){const a=choose(s,policy);if(!a)break;const before={turn:s.turn,hp:s.hp,enemyHp:s.enemyHp,energy:s.energy,nitro:s.nitro,enemyIntent:s.enemyIntent,availableCards:[...s.hand]};const ok=resolve(s,a);n++;if(trace)s.trace.push({...before,action:a.kind==='redline'?'REDLINE+'+a.id:a.id,energyAfter:s.energy,nitroAfter:s.nitro});if(!ok||s.enemyHp<=0||s.hp<=0)break}s.energyWaste+=s.energy;if(s.enemyHp>0&&s.hp>0)enemy(s);draw(s,2);s.turn++}return{seed,nitroOn,win:s.enemyHp<=0&&s.hp>0,turns:Math.min(s.turn,20),energySpent:s.energySpent,energyWaste:s.energyWaste,nitroGenerated:s.nitroGenerated,nitroSpent:s.nitroSpent,nitroRemaining:s.nitro,redlineUses:s.redlineUses,redlineFailures:s.redlineFailures,cardUses:s.cardUses,actions:s.actions,deathCause:s.deathCause,enemyResponses:s.enemyResponses,counterActions:s.counterActions,trace:s.trace}}

export function aggregate(rs){const wins=rs.filter(x=>x.win).length,uses={};for(const r of rs)for(const[k,v]of Object.entries(r.cardUses))uses[k]=(uses[k]||0)+v;const total=Object.values(uses).reduce((a,b)=>a+b,0);return{simulations:rs.length,winRate:pct(wins,rs.length),lossRate:1-pct(wins,rs.length),avgTurns:mean(rs.map(x=>x.turns)),medianTurns:median(rs.map(x=>x.turns)),avgEnergySpent:mean(rs.map(x=>x.energySpent)),avgEnergyWaste:mean(rs.map(x=>x.energyWaste)),avgNitroGenerated:mean(rs.map(x=>x.nitroGenerated)),avgNitroSpent:mean(rs.map(x=>x.nitroSpent)),avgNitroRemaining:mean(rs.map(x=>x.nitroRemaining)),redlineActivationRate:pct(rs.filter(x=>x.redlineUses>0).length,rs.length),avgRedlineUses:mean(rs.map(x=>x.redlineUses)),cardUsage:uses,cardUsageShare:Object.fromEntries(Object.entries(uses).map(([k,v])=>[k,pct(v,total)])),enemyResponseFrequency:mean(rs.map(x=>x.enemyResponses)),counterActionFrequency:mean(rs.map(x=>x.counterActions)),deathCauses:rs.reduce((m,x)=>{if(x.deathCause)m[x.deathCause]=(m[x.deathCause]||0)+1;return m},{} )}}

export function paired(seed,policy='adaptive',enemyType='basic',variance='normal'){const c=run(seed,false,policy,enemyType,false,variance),n=run(seed,true,policy,enemyType,false,variance),max=Math.max(c.actions.length,n.actions.length);let div=0;for(let i=0;i<max;i++)if(c.actions[i]!==n.actions[i])div++;const timing=Math.abs(c.turns-n.turns)+c.actions.map((x,i)=>x.startsWith('REDLINE')!==n.actions[i]?.startsWith('REDLINE')).filter(Boolean).length;return{seed,control:c,nitro:n,actionDivergenceCount:div,actionDiverged:div>0,timingDivergenceScore:timing}}
function matrix(on){const states=[['LOW_NITRO',70,90,10,'DEFEND'],['MEDIUM_NITRO',70,90,50,'DEFEND'],['HIGH_NITRO',70,90,80,'DEFEND'],['ATTACK_PRESSURE',50,70,60,'ATTACK'],['DEFEND_WINDOW',80,55,60,'DEFEND'],['SPECIAL_WINDOW',80,55,60,'SPECIAL']],o={};for(const[n,h,e,ni,i]of states){const s={nitroOn:on,enemyIntent:i,hp:h,enemyHp:e,nitro:ni,energy:3,hand:['shot','guard','pump','ram']};o[n]={shot:cardScore(s,'shot'),guard:cardScore(s,'guard'),pump:cardScore(s,'pump'),ram:cardScore(s,'ram')}}return o}

export function experiment(){const models={},policies={},rngProfiles={},enemyIntent={},pairs=SEEDS.map(s=>paired(s));for(const on of [false,true])models[on?'nitro_on':'nitro_off']=aggregate(SEEDS.map(s=>run(s,on)));for(const p of POLICIES)for(const e of ENEMIES){policies['off:'+e+':'+p]=aggregate(SEEDS.map(s=>run(s,false,p,e)));policies['on:'+e+':'+p]=aggregate(SEEDS.map(s=>run(s,true,p,e)))}for(const v of ['low','normal','high'])rngProfiles[v]={off:aggregate(SEEDS.map(s=>run(s,false,'adaptive','basic',false,v))),on:aggregate(SEEDS.map(s=>run(s,true,'adaptive','basic',false,v)))}for(const e of ENEMIES)enemyIntent[e]={off:aggregate(SEEDS.map(s=>run(s,false,'adaptive',e))),on:aggregate(SEEDS.map(s=>run(s,true,'adaptive',e)))}const d=pairs.filter(x=>x.actionDiverged),t=pairs.filter(x=>x.timingDivergenceScore>0),sp=models.nitro_on;const out={config:CONFIG,cardPool:CARDS,deck:DECK,enemyPool:ENEMIES,policies:POLICIES,models,policiesResults:policies,rngProfiles,enemyIntent,pairedSummary:{seeds:10000,actionDivergenceRate:pct(d.length,pairs.length),divergentSeeds:d.slice(0,25).map(x=>x.seed),avgTimingDivergenceScore:mean(pairs.map(x=>x.timingDivergenceScore)),timingDivergenceRate:pct(t.length,pairs.length),winOutcomeDivergenceRate:pct(pairs.filter(x=>x.control.win!==x.nitro.win).length,pairs.length)},nitroSpendingDistribution:{ramShareOfAllCardUses:sp.cardUsageShare.ram||0,ramShareOfNitroSpenderActions:pct(sp.cardUsage.ram||0,(sp.cardUsage.ram||0)+(sp.cardUsage.pump||0)),cardUsage:sp.cardUsage,cardUsageShare:sp.cardUsageShare},cardValueShift:{control:matrix(false),nitro:matrix(true)},traces:SEEDS.slice(0,10).map(seed=>({seed,control:run(seed,false,'adaptive','basic',true).trace,nitro:run(seed,true,'adaptive','basic',true).trace})),determinism:{samePairedResults:JSON.stringify(SEEDS.slice(0,100).map(s=>paired(s)))===JSON.stringify(SEEDS.slice(0,100).map(s=>paired(s)))},limitations:['Heuristic policies are proxies, not human subjects.','Same seed is paired, but state divergence can change later RNG consumption.','Card value is a model score, not measured player utility.','No production integration was performed.']};fs.writeFileSync('/tmp/rbp_phase4_results.json',JSON.stringify(out,null,2));return out}
if(import.meta.url===`file://${process.argv[1]}`){const o=experiment();console.log(JSON.stringify({models:o.models,pairedSummary:o.pairedSummary,nitroSpendingDistribution:o.nitroSpendingDistribution,determinism:o.determinism},null,2))}
