const CONFIG={simulations:10000,seedStart:100001,maxTurns:20,handSize:4,energyPerTurn:3,playerMaxHp:100,enemyMaxHp:150,enemyAttack:45,nitroGenerate:35,ramNitroCost:40,guardNitroCost:25,redlineNitroCost:25,redlineDamageMultiplier:1.25,redlineIncomingMultiplier:1.25,varianceProfiles:{low:[.98,1.02],normal:[.9,1.1],high:[.75,1.25]}};
const CARDS={shot:{cost:1,damage:18},guard:{cost:1,block:14},pump:{cost:1,damage:7},ram:{cost:2,damage:26}};
const DECK=['shot','shot','guard','pump','ram','guard','ram']; const ENEMIES=['basic','reactive','pressure']; const POLICIES=['aggressive','defensive','generator','redline','adaptive']; const SEEDS=Array.from({length:10000},(_,i)=>100001+i);
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0, median=a=>{a=[...a].sort((a,b)=>a-b);return a[Math.floor(a.length/2)]||0}, pct=(n,d)=>d?n/d:0;
const rng=seed=>{let s=(seed>>>0)||0x6d2b79f5;return()=>{s^=s<<13;s^=s>>>17;s^=s<<5;s>>>=0;return s/4294967296}}; const shuffle=(a,r)=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(r()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function state(seed,model,enemyType='basic',variance='normal'){const r=rng(seed);return{seed,model,redlineOn:model==='B'||model==='C',nitroOn:true,enemyType,variance,r,turn:1,hp:100,enemyHp:150,energy:3,block:0,nitro:0,enemyIntent:'ATTACK',redlinePending:false,hand:[],drawPile:shuffle(DECK,r),discard:[],actions:[],trace:[],cardUses:{},energySpent:0,energyWaste:0,nitroGenerated:0,nitroSpent:0,redlineUses:0,redlineExtraDamage:0,redlineExtraIncoming:0,redlineRiskEvents:0,redlineOpportunities:0,redlineMissed:0,ramNitroUses:0,guardNitroUses:0,redlineOppByIntent:{},redlineActByIntent:{},redlineOppByHp:{},redlineActByHp:{},redlineOppByEnemyHp:{},redlineActByEnemyHp:{},redlineOppByNitro:{},redlineActByNitro:{},deathCause:null};}
function draw(s,n){for(let i=0;i<n;i++){if(s.hand.length>=4)break;if(!s.drawPile.length){s.drawPile=shuffle(s.discard,s.r);s.discard=[]}const c=s.drawPile.shift();if(c)s.hand.push(c)}}
function intent(s){const x=s.r();if(s.enemyType==='reactive')s.enemyIntent=x<.45?'ATTACK':x<.75?'DEFEND':'SPECIAL';else if(s.enemyType==='pressure')s.enemyIntent=s.turn%3===0?'SPECIAL':x<.7?'ATTACK':'DEFEND';else s.enemyIntent=x<.7?'ATTACK':'DEFEND'}
function legal(s,id){return !!CARDS[id]&&s.energy>=CARDS[id].cost}
function score(s,id){if(!legal(s,id))return-Infinity; if(id==='shot')return 18+(s.enemyIntent==='DEFEND'?2:0); if(id==='guard')return s.enemyIntent==='ATTACK'?(s.hp<60?40:22):5; if(id==='pump')return s.nitro<50?15:2; if(id==='ram')return 26+(s.nitro>=40?14:0)+(s.enemyHp<=48?8:0)+(s.nitro<40?-3:0); return -Infinity}
function best(s){return s.hand.filter(id=>legal(s,id)).sort((a,b)=>score(s,b)-score(s,a))[0]||null}
function binHp(v){return v>=67?'high':v>=34?'mid':'low'}
function binEnemyHp(v){return v>=101?'high':v>=51?'mid':'low'}
function binNitro(v){return v>=70?'high':v>=40?'mid':'low'}
function bump(o,k){o[k]=(o[k]||0)+1}
function choose(s,p,model){const l=s.hand.filter(id=>legal(s,id));if(!l.length)return null;
 if(p==='defensive'&&s.enemyIntent==='ATTACK'&&l.includes('guard'))return{id:'guard',kind:'card'};
 if((model==='A'||model==='B')&&s.nitro>=25&&s.enemyIntent==='ATTACK'&&s.hp<70&&l.includes('guard')&&p!=='generator')return{id:'guard',kind:'guardNitro'};
 if(p==='generator'&&l.includes('pump')&&s.nitro<55)return{id:'pump',kind:'card'};
 if(p==='redline'&&(model==='B'||model==='C')&&s.nitro>=25&&s.hp>=55){const id=best(s);if(id)return{id,kind:'redline'}}
 if(p==='adaptive'){
   if(s.enemyIntent==='ATTACK'&&s.hp<55&&l.includes('guard'))return{id:'guard',kind:'card'};
   if(s.nitro<35&&s.enemyIntent!=='ATTACK'&&l.includes('pump'))return{id:'pump',kind:'card'};
   if(s.nitro>=40&&l.includes('ram')&&(s.enemyHp<=55||s.energy>=2))return{id:'ram',kind:'card',ramSpend:true};
   if((model==='B'||model==='C')&&s.nitro>=25&&s.hp>=55){const id=best(s);if(id)return{id,kind:'redline'}}
 }
 return{id:best(s),kind:'card'};
}
function damage(s,d){if(d<=0)return 0;const v=CONFIG.varianceProfiles[s.variance];const dealt=Math.max(0,Math.round(d*(v[0]+(v[1]-v[0])*s.r())));s.enemyHp=Math.max(0,s.enemyHp-dealt);return dealt}
function play(s,id,opts={}){const d=CARDS[id];if(!d||s.energy<d.cost)return false;s.energy-=d.cost;s.energySpent+=d.cost;const i=s.hand.indexOf(id);if(i>=0){s.hand.splice(i,1);s.discard.push(id)}s.cardUses[id]=(s.cardUses[id]||0)+1;let raw=d.damage;if(id==='guard')s.block+=d.block;
 if(id==='pump'){s.nitro=Math.min(100,s.nitro+35);s.nitroGenerated+=35;raw=7}
 if(id==='ram'&&opts.ramSpend){s.nitro-=40;s.nitroSpent+=40;s.ramNitroUses++;raw+=14;s.actions.push('NITRO+ram')}
 let dealt=0;if(raw>0){const mult=opts.redline?CONFIG.redlineDamageMultiplier:1;dealt=damage(s,raw*mult);if(opts.redline)s.redlineExtraDamage+=dealt;}
 s.actions.push(opts.redline?'REDLINE+'+id:id);return true}
function resolve(s,a){if(!a)return false;if(a.kind==='guardNitro'){if(s.nitro<25||!legal(s,'guard'))return false;s.nitro-=25;s.nitroSpent+=25;s.guardNitroUses++;s.actions.push('NITRO+guard');return play(s,'guard')}if(a.kind==='redline'){if(s.nitro<25||!legal(s,a.id))return false;s.nitro-=25;s.nitroSpent+=25;s.redlineUses++;s.redlinePending=true;return play(s,a.id,{redline:true})}return play(s,a.id,{ramSpend:a.ramSpend})}
function enemy(s){let base=s.enemyIntent==='ATTACK'?45:s.enemyIntent==='SPECIAL'?18:0;let d=base;if(s.redlinePending){const extra=Math.round(d*(CONFIG.redlineIncomingMultiplier-1));s.redlineExtraIncoming+=extra;if(extra>0)s.redlineRiskEvents++;d=Math.round(d*CONFIG.redlineIncomingMultiplier);s.redlinePending=false;s.trace.push({turn:s.turn,event:'REDLINE_RISK',intent:s.enemyIntent,incomingBase:base,incomingFinal:d,extraIncoming:extra,enemyHp:s.enemyHp,hp:s.hp,nitro:s.nitro});}
 const b=Math.min(s.block,d);s.block-=b;d-=b;s.hp=Math.max(0,s.hp-d);if(s.hp<=0)s.deathCause=s.enemyIntent==='SPECIAL'?'ENEMY_SPECIAL':'ENEMY_ATTACK';
 if(s.enemyType==='reactive'&&s.enemyIntent==='SPECIAL'){}}
function run(seed,model='A',policy='adaptive',enemyType='basic',variance='normal',captureTrace=false){const s=state(seed,model,enemyType,variance);draw(s,4);while(s.turn<=20&&s.hp>0&&s.enemyHp>0){s.energy=3;s.block=0;intent(s);let n=0;while(s.energy>0&&s.hp>0&&s.enemyHp>0&&n<3){const legalBefore=s.hand.filter(id=>legal(s,id));const redlineEligible=s.redlineOn&&s.nitro>=25&&legalBefore.length>0;
 if(redlineEligible){s.redlineOpportunities++;bump(s.redlineOppByIntent,s.enemyIntent);bump(s.redlineOppByHp,binHp(s.hp));bump(s.redlineOppByEnemyHp,binEnemyHp(s.enemyHp));bump(s.redlineOppByNitro,binNitro(s.nitro));}
 let a=choose(s,policy,model);const pre={turn:s.turn,hp:s.hp,enemyHp:s.enemyHp,nitro:s.nitro,energy:s.energy,intent:s.enemyIntent,hand:[...s.hand],redlineEligible};
 if(a&&a.kind!=='redline'&&redlineEligible)s.redlineMissed++;
 if(a&&a.id==='ram'&&s.nitro>=40&&model!=='C')a={...a,ramSpend:true};
 if(model==='A'&&a?.kind==='redline')a={id:a.id,kind:'card'};
 if(a?.kind==='redline'){bump(s.redlineActByIntent,s.enemyIntent);bump(s.redlineActByHp,binHp(s.hp));bump(s.redlineActByEnemyHp,binEnemyHp(s.enemyHp));bump(s.redlineActByNitro,binNitro(s.nitro));}
 const ok=resolve(s,a);if(captureTrace)s.trace.push({...pre,chosen:a,ok,post:{hp:s.hp,enemyHp:s.enemyHp,nitro:s.nitro,energy:s.energy}});n++;if(!ok||s.enemyHp<=0||s.hp<=0)break;}s.energyWaste+=s.energy;if(s.enemyHp>0&&s.hp>0)enemy(s);draw(s,2);s.turn++}
 return{seed,model,policy,win:s.enemyHp<=0&&s.hp>0,turns:Math.min(s.turn,20),energySpent:s.energySpent,energyWaste:s.energyWaste,nitroGenerated:s.nitroGenerated,nitroSpent:s.nitroSpent,nitroRemaining:s.nitro,cardUses:s.cardUses,actions:s.actions,deathCause:s.deathCause,redlineUses:s.redlineUses,redlineExtraDamage:s.redlineExtraDamage,redlineExtraIncoming:s.redlineExtraIncoming,redlineRiskEvents:s.redlineRiskEvents,redlineOpportunities:s.redlineOpportunities,redlineMissed:s.redlineMissed,redlineOppByIntent:s.redlineOppByIntent,redlineActByIntent:s.redlineActByIntent,redlineOppByHp:s.redlineOppByHp,redlineActByHp:s.redlineActByHp,redlineOppByEnemyHp:s.redlineOppByEnemyHp,redlineActByEnemyHp:s.redlineActByEnemyHp,redlineOppByNitro:s.redlineOppByNitro,redlineActByNitro:s.redlineActByNitro,ramNitroUses:s.ramNitroUses,guardNitroUses:s.guardNitroUses,trace:s.trace};}
function aggregate(rs){const uses={},sp={ram:0,guard:0,redline:0};for(const r of rs){for(const[k,v]of Object.entries(r.cardUses))uses[k]=(uses[k]||0)+v;for(const a of r.actions){if(a==='NITRO+ram')sp.ram++;if(a.startsWith('REDLINE+'))sp.redline++;if(a==='NITRO+guard')sp.guard++;}}const mergeMaps=(field)=>rs.reduce((acc,r)=>{for(const[k,v]of Object.entries(r[field]||{}))acc[k]=(acc[k]||0)+v;return acc},{});const total=Object.values(uses).reduce((a,b)=>a+b,0),st=Object.values(sp).reduce((a,b)=>a+b,0);return{simulations:rs.length,winRate:pct(rs.filter(x=>x.win).length,rs.length),avgTurns:mean(rs.map(x=>x.turns)),medianTurns:median(rs.map(x=>x.turns)),energySpent:mean(rs.map(x=>x.energySpent)),energyWaste:mean(rs.map(x=>x.energyWaste)),nitroGenerated:mean(rs.map(x=>x.nitroGenerated)),nitroSpent:mean(rs.map(x=>x.nitroSpent)),nitroSpendFrequency:pct(rs.filter(x=>x.nitroSpent>0).length,rs.length),cardUsage:uses,cardUsageShare:Object.fromEntries(Object.entries(uses).map(([k,v])=>[k,pct(v,total)])),nitroAllocation:Object.fromEntries(Object.entries(sp).map(([k,v])=>[k,pct(v,st)])),nitroSpendEvents:sp,redlineActivationRate:pct(rs.filter(x=>x.redlineUses>0).length,rs.length),redlineUses:rs.reduce((a,r)=>a+r.redlineUses,0),redlineExtraDamage:mean(rs.map(r=>r.redlineExtraDamage)),redlineExtraIncoming:mean(rs.map(r=>r.redlineExtraIncoming)),redlineRiskEvents:rs.reduce((a,r)=>a+r.redlineRiskEvents,0),redlineOpportunityCount:rs.reduce((a,r)=>a+r.redlineOpportunities,0),redlineMissedOpportunityCount:rs.reduce((a,r)=>a+r.redlineMissed,0),redlineByIntent:{opportunities:mergeMaps('redlineOppByIntent'),activations:mergeMaps('redlineActByIntent')},redlineByPlayerHp:{opportunities:mergeMaps('redlineOppByHp'),activations:mergeMaps('redlineActByHp')},redlineByEnemyHp:{opportunities:mergeMaps('redlineOppByEnemyHp'),activations:mergeMaps('redlineActByEnemyHp')},redlineByNitro:{opportunities:mergeMaps('redlineOppByNitro'),activations:mergeMaps('redlineActByNitro')},deathCauses:rs.reduce((m,r)=>{if(r.deathCause)m[r.deathCause]=(m[r.deathCause]||0)+1;return m},{})};}
function policyResults(model){const out={};for(const p of POLICIES)out[p]=aggregate(SEEDS.map(s=>run(s,model,p)));return out}
function pairedAB(policy='adaptive'){const ps=SEEDS.map(s=>{const a=run(s,'A',policy),b=run(s,'B',policy);const n=Math.max(a.actions.length,b.actions.length);let ad=0;for(let i=0;i<n;i++)if(a.actions[i]!==b.actions[i])ad++;let td=0;for(let i=0;i<n;i++)if((a.actions[i]||'').startsWith('REDLINE')!== (b.actions[i]||'').startsWith('REDLINE'))td++;return{action:ad>0,timing:td>0,outcome:a.win!==b.win,actionCount:ad,timingCount:td};});return{actionDivergenceRate:pct(ps.filter(x=>x.action).length,ps.length),timingDivergenceRate:pct(ps.filter(x=>x.timing).length,ps.length),outcomeDivergenceRate:pct(ps.filter(x=>x.outcome).length,ps.length),avgActionDivergence:mean(ps.map(x=>x.actionCount)),avgTimingDivergence:mean(ps.map(x=>x.timingCount))}}
function counterfactuals(){const states=[{id:1,hp:85,enemyHp:120,nitro:80,intent:'ATTACK'},{id:2,hp:35,enemyHp:90,nitro:80,intent:'ATTACK'},{id:3,hp:60,enemyHp:45,nitro:80,intent:'DEFEND'},{id:4,hp:60,enemyHp:140,nitro:50,intent:'SPECIAL'}];const chooseState=(x,model)=>{const s={...x,model,energy:3,hand:['shot','guard','pump','ram'],redlineOn:model==='B',nitro:x.nitro};const base=best(s);if(model==='B'&&s.nitro>=25&&s.hp>=55){const id=best(s);return{id:'REDLINE+'+id,reason:'Nitro >=25, a legal card exists, and player HP is at least 55; Redline modifies that card and arms the next enemy-hit multiplier.'}}return{id:base,reason:'No Redline trigger under the declared policy rule.'}};return states.map(x=>({state:x,redlineOff:chooseState(x,'A'),redlineOn:chooseState(x,'B')}));}
function runExperiment(){const A=aggregate(SEEDS.map(s=>run(s,'A'))),B=aggregate(SEEDS.map(s=>run(s,'B')));const policies={A:policyResults('A'),B:policyResults('B')};const spreads={A:Math.max(...Object.values(policies.A).map(x=>x.winRate))-Math.min(...Object.values(policies.A).map(x=>x.winRate)),B:Math.max(...Object.values(policies.B).map(x=>x.winRate))-Math.min(...Object.values(policies.B).map(x=>x.winRate))};return{config:CONFIG,seeds:{start:100001,end:110000,count:10000},constantVariables:['card pool','deck','enemy pool','enemy intent','enemy behavior','policies','Energy','RNG','damage variance','max turns','seed set'],variable:'Redline OFF vs Redline ON for A/B',modelDefinitions:{A:'Nitro + Ram + Guard, Redline OFF. Pump generates 35 Nitro; Ram may spend 40 for +14 damage; Guard may spend 25 Nitro for its existing 14 block.',B:'Nitro + Ram + Guard + Redline ON. Same as A plus Redline: spend 25 Nitro before a legal card; that card damage is multiplied by 1.25; next enemy hit is multiplied by 1.25.',C:'NOT RUN: optional isolated Redline model omitted; mandatory A/B comparison is the causal experiment.'},models:{A,B,B_minus_A:{winRateDelta:B.winRate-A.winRate,avgTurnsDelta:B.avgTurns-A.avgTurns,energyWasteDelta:B.energyWaste-A.energyWaste,nitroSpentDelta:B.nitroSpent-A.nitroSpent}},pairedAB:pairedAB('adaptive'),policyWinRates:policies,dominanceSpread:spreads,context:{enemyIntent:B.redlineByIntent,playerHp:B.redlineByPlayerHp,enemyHp:B.redlineByEnemyHp,nitro:B.redlineByNitro},counterfactuals:counterfactuals(),determinism:{A:JSON.stringify(SEEDS.slice(0,250).map(s=>run(s,'A')))==JSON.stringify(SEEDS.slice(0,250).map(s=>run(s,'A'))),B:JSON.stringify(SEEDS.slice(0,250).map(s=>run(s,'B')))==JSON.stringify(SEEDS.slice(0,250).map(s=>run(s,'B')))},limitations:['Policies are heuristic, not human players.','A/B share initial seeds but diverging traces can consume later RNG differently.','Redline value/risk metrics are simulator-defined quantities, not player preferences.']};}
export {CONFIG,CARDS,DECK,ENEMIES,POLICIES,SEEDS,run,runExperiment,counterfactuals};
if (import.meta.url === `file://${process.argv[1]}`) { console.log(JSON.stringify(runExperiment(),null,2)); }