import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {runPhase9,runTests} from './phase9_forced_choice.mjs';
const here=path.dirname(fileURLToPath(import.meta.url));
const source=fs.readFileSync(path.resolve(here,'../rocket_bunny_phase6/phase6_redline.mjs'),'utf8');
const result=runPhase9(source);
assert.equal(result.seeds.count,10000);
assert.equal(result.candidateCounts.setA,9548);
assert.equal(result.candidateCounts.setB,1687);
assert.equal(result.candidateCounts.setC,961);
assert.equal(result.candidateCounts.union,10274);
assert.equal(result.sets.noSpenderAvailable,9406);
assert.equal(result.sets.A.withNoSpender,8680);
assert.equal(result.sets.B.withNoSpender,1552);
assert.equal(result.sets.C.withNoSpender,826);
assert.equal(result.comparisons.A_Redline_vs_Guard.n,9548);
assert.equal(result.comparisons.B_Redline_vs_Ram.n,1687);
assert.equal(result.comparisons.C_Redline_vs_Guard.n,961);
assert.equal(result.determinism,true);
assert.equal(result.tests,'PASS');
assert.equal(runTests(source),'PASS');
console.log('phase9_forced_choice.test.mjs: PASS');