import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const SEED_START=100001,SEED_COUNT=10000,SEEDS=Array.from({length:SEED_COUNT},(_,i)=>SEED_START+i);

export function stateKey(s){return JSON.stringify({turn:s.turn,hp:s.hp,enemyHp:s.enemyHp,energy:s.energy,nitro:s.nitro,intent:s.enemyIntent,hand:s.hand,drawPile:s.drawPile,discard:s.discard,redlinePending:s.redlinePending,block:s.block,rngState:s.r.state});}
function instrumentPhase6(source){
 let x=source; x="function stateKey(s){return JSON.stringify({turn:s.turn,hp:s.hp,enemyHp:s.enemyHp,energy:s.energy,nitro:s.nitro,intent:s.enemyIntent,hand:s.hand,drawPile:s.drawPile,discard:s.discard,redlinePending:s.redlinePending,block:s.block,rngState:s.r.state});}\n"+x;
 x=x.replace(/const rng=seed=>\{let s=\(seed>>>0\)\|\|0x6d2b79f5;return\(\)=>\{s\^=s<<13;s\^=s>>>17;s\^=s<<5;s>>>=0;return s\/4294967296\}\};/,"const rng=seed=>{let s=(seed>>>0)||0x6d2b79f5;const f=()=>{s^=s<<13;s^=s>>>17;s^=s<<5;s>>>=0;return s/4294967296};Object.defineProperty(f,'state',{get:()=>s});return f};");
 x=x.replace(/function choose\(s,p,model\)\{const l=s\.hand\.filter\(id=>legal\(s,id\)\);if\(!l\.length\)return null;/,"function choose(s,p,model){const force=globalThis.__RB9_FORCE_HOOK;const fk=stateKey(s);if(force&&force.key===fk){if(force.action==='REDLINE'){const id=force.card||best(s);return id?{id,kind:'redline'}:null}if(force.action==='GUARD')return{id:'guard',kind:'guardNitro'};if(force.action==='RAM')return{id:'ram',kind:'card',ramSpend:true};if(force.action==='NO_SPENDER'){if(s.hand.includes('shot')&&legal(s,'shot'))return{id:'shot',kind:'card'};return null}}const l=s.hand.filter(id=>legal(s,id));if(!l.length)return null;");
 x=x.replace(/const pre=\{turn:s\.turn,hp:s\.hp,enemyHp:s\.enemyHp,nitro:s\.nitro,energy:s\.energy,intent:s\.enemyIntent,hand:\[\.\.\.s\.hand\],redlineEligible\};/,"const pre={turn:s.turn,hp:s.hp,enemyHp:s.enemyHp,nitro:s.nitro,energy:s.energy,intent:s.enemyIntent,hand:[...s.hand],redlineEligible,availableActions:[...legalBefore],currentCard:null,deckState:[...s.drawPile],discardState:[...s.discard],enemyState:{type:s.enemyType,intent:s.enemyIntent,hp:s.enemyHp},rngState:s.r.state,redlinePending:s.redlinePending,block:s.block,stateKey:stateKey(s)};");
 x=x.replace(/if\(captureTrace\)s\.trace\.push\(\{\.\.\.pre,chosen:a,ok,post:\{hp:s\.hp,enemyHp:s\.enemyHp,nitro:s\.nitro,energy:s\.energy\}\}\);/,"if(captureTrace)s.trace.push({...pre,chosen:a,ok,post:{hp:s.hp,enemyHp:s.enemyHp,nitro:s.nitro,energy:s.energy,block:s.block,rngState:s.r.state,hand:[...s.hand],discard:[...s.discard],drawPile:[...s.drawPile]}});const forcedStop=globalThis.__RB9_FORCE_HOOK&&globalThis.__RB9_FORCE_HOOK.key===pre.stateKey;n++;if(forcedStop||!ok||s.enemyHp<=0||s.hp<=0)break;");
 x=x.replace(/if\(s\.enemyHp>0&&s\.hp>0\)enemy\(s\);/,"if(s.enemyHp>0&&s.hp>0){const hpBefore=s.hp;const intentBefore=s.enemyIntent;enemy(s);s.trace.push({event:'ENEMY_RESOLUTION',turn:s.turn,intent:intentBefore,incomingBase:intentBefore==='ATTACK'?45:intentBefore==='SPECIAL'?18:0,incomingRawFinal:intentBefore==='ATTACK'?Math.round(45*1.25):intentBefore==='SPECIAL'?Math.round(18*1.25):0,incomingFinal:hpBefore-s.hp,hpBefore,hpAfter:s.hp});}");
 x=x.replace(/export \{CONFIG,CARDS,DECK,ENEMIES,POLICIES,SEEDS,run,runExperiment,counterfactuals\};/,'');
 x=x.replace(/if \(import\.meta\.url[^\n]+/,'');
 return x;
}
export function loadInstrumented(source){return new Function(instrumentPhase6(source)+";return {CONFIG,CARDS,DECK,ENEMIES,POLICIES,SEEDS,run,runExperiment,counterfactuals};")();}
export function freezeFromTrace(t){return {seed:t.seed,turn:t.turn,playerHP:t.hp,enemyHP:t.enemyHp,energy:t.energy,nitro:t.nitro,enemyIntent:t.intent,currentCard:t.currentCard,hand:[...t.hand],deckState:[...t.deckState],discardState:[...t.discardState],enemyState:{...t.enemyState},rngState:t.rngState,availableActions:[...t.availableActions],redlineLegal:true,guardLegal:t.availableActions.includes('guard')&&t.nitro>=25,ramLegal:t.availableActions.includes('ram')&&t.nitro>=40,stateKey:t.stateKey};}
function runForced(runner,frozen,action){globalThis.__RB9_FORCE_HOOK={key:frozen.stateKey,action};try{const result=runner.run(frozen.seed,'B','adaptive','basic','normal',true),idx=result.trace.findIndex(t=>t.stateKey===frozen.stateKey);if(idx<0)throw new Error('forced state not reached');return {result,trace:result.trace[idx],enemyEvent:result.trace.slice(idx+1).find(e=>e.event==='ENEMY_RESOLUTION'&&e.turn===frozen.turn)};}finally{delete globalThis.__RB9_FORCE_HOOK;}}
function branchMetrics(f,b){const t=b.trace,e=b.enemyEvent;return {forcedAction:t.chosen?.kind==='redline'?'REDLINE':t.chosen?.id?.toUpperCase()||'UNAVAILABLE',affectedCard:t.chosen?.id||null,nitroCost:t.chosen?.kind==='redline'?25:t.chosen?.kind==='guardNitro'?25:(t.chosen?.id==='ram'&&t.chosen?.ramSpend?40:0),nitroBefore:f.nitro,nitroAfter:t.post.nitro,nitroConsumed:f.nitro-t.post.nitro,playerHPBefore:f.playerHP,playerHPAfter:e?e.hpAfter:t.post.hp,playerHPDelta:(e?e.hpAfter:t.post.hp)-f.playerHP,enemyHPBefore:f.enemyHP,enemyHPAfter:t.post.enemyHp,enemyHPDelta:t.post.enemyHp-f.enemyHP,damageDealt:f.enemyHP-t.post.enemyHp,damageReceived:e?e.hpBefore-e.hpAfter:0,energyBefore:f.energy,energyAfter:t.post.energy,energySpent:f.energy-t.post.energy,turnImpact:b.result.turns-f.turn,enemyResponse:e?{intent:e.intent,incomingBase:e.incomingBase,incomingRawFinal:e.incomingRawFinal,incomingAfterBlock:e.incomingFinal}:null,redlineRiskEvent:Boolean(e&&t.chosen?.kind==='redline'&&e.incomingRawFinal>e.incomingBase),redlineAmplifiedIncoming:e&&t.chosen?.kind==='redline'?e.incomingRawFinal-e.incomingBase:0,rngStateBefore:f.rngState,rngStateAfter:t.post.rngState};}
export function comparePair(f,r,actions){const out={};for(const a of actions)out[a]=branchMetrics(f,runForced(r,f,a));return out;}
export function extractCandidates(runner){const sets={A:[],B:[],C:[]},seen={A:new Set(),B:new Set(),C:new Set()};for(const seed of SEEDS){const r=runner.run(seed,'B','adaptive','basic','normal',true);for(const t of r.trace){if(!t.redlineEligible)continue;const f=freezeFromTrace({...t,seed});if(f.guardLegal&&!seen.A.has(f.stateKey)){seen.A.add(f.stateKey);sets.A.push(f);}if(f.ramLegal&&!seen.B.has(f.stateKey)){seen.B.add(f.stateKey);sets.B.push(f);}if(f.guardLegal&&f.ramLegal&&!seen.C.has(f.stateKey)){seen.C.add(f.stateKey);sets.C.push(f);}}}return sets;}
function avg(rows,k){return rows.length?rows.reduce((s,r)=>s+r[k],0)/rows.length:0;}
function aggregateRows(rows){return {n:rows.length,meanNitroCost:avg(rows,'nitroCost'),meanNitroConsumed:avg(rows,'nitroConsumed'),meanDamage:avg(rows,'damageDealt'),meanDamageReceived:avg(rows,'damageReceived'),meanPlayerHPDelta:avg(rows,'playerHPDelta'),meanEnemyHPDelta:avg(rows,'enemyHPDelta'),meanEnergySpent:avg(rows,'energySpent'),meanTurnImpact:avg(rows,'turnImpact'),riskEvents:rows.filter(r=>r.redlineRiskEvent).length};}
function summarize(group){const p=k=>group.filter(r=>r.branches[k]).map(r=>r.branches[k]);const red=p('REDLINE');const affected=red.reduce((m,r)=>{if(r.affectedCard)m[r.affectedCard]=(m[r.affectedCard]||0)+1;return m},{});return {states:group.length,withNoSpender:group.filter(r=>r.branches.NO_SPENDER).length,redline:{...aggregateRows(red),affectedCardCounts:affected},guard:aggregateRows(p('GUARD')),ram:aggregateRows(p('RAM')),noSpender:aggregateRows(p('NO_SPENDER'))};}
function deltas(group,left,right){const rows=group.filter(r=>r.branches[left]&&r.branches[right]).map(r=>{const a=r.branches[left],b=r.branches[right];return {nitroCost:a.nitroCost-b.nitroCost,nitroConsumed:a.nitroConsumed-b.nitroConsumed,damageDealt:a.damageDealt-b.damageDealt,damageReceived:a.damageReceived-b.damageReceived,playerHPDelta:a.playerHPDelta-b.playerHPDelta,enemyHPDelta:a.enemyHPDelta-b.enemyHPDelta,energySpent:a.energySpent-b.energySpent,turnImpact:a.turnImpact-b.turnImpact,riskEvent:false};});return aggregateRows(rows);}
function manualCounterfactuals(){const s=[{id:'A',playerHP:90,enemyHP:80,energy:2,nitro:80,enemyIntent:'ATTACK'},{id:'B',playerHP:35,enemyHP:80,energy:2,nitro:80,enemyIntent:'ATTACK'},{id:'C',playerHP:90,enemyHP:25,energy:2,nitro:80,enemyIntent:'DEFEND'},{id:'D',playerHP:50,enemyHP:100,energy:2,nitro:50,enemyIntent:'SPECIAL'}];return s.map(x=>({...x,classification:'MANUALLY CONSTRUCTED',assumptions:'hand=[shot,guard,pump,ram]; nominal values only; no composite utility.',Redline:{nitroCost:25,affectedCard:'Ram',nominalDamage:50,bonusDamage:10,incoming:x.enemyIntent==='ATTACK'?56:x.enemyIntent==='SPECIAL'?23:0},Guard:{nitroCost:25,block:14,incomingAfterBlock:x.enemyIntent==='ATTACK'?31:x.enemyIntent==='SPECIAL'?4:0},Ram:{nitroCost:40,nominalDamage:40,incoming:x.enemyIntent==='ATTACK'?45:x.enemyIntent==='SPECIAL'?18:0},NoSpender:{available:true,action:'Shot',nominalDamage:18,incoming:x.enemyIntent==='ATTACK'?45:x.enemyIntent==='SPECIAL'?18:0}}));}
export function runPhase9(source){const runner=loadInstrumented(source),candidates=extractCandidates(runner),union=new Map();for(const f of [...candidates.A,...candidates.B])if(!union.has(f.stateKey))union.set(f.stateKey,f);const all=[...union.values()],rows=[];for(const f of all){const actions=['REDLINE'];if(f.guardLegal)actions.push('GUARD');if(f.ramLegal)actions.push('RAM');if(f.availableActions.includes('shot'))actions.push('NO_SPENDER');rows.push({frozen:f,branches:comparePair(f,runner,actions)});}const A=rows.filter(r=>r.frozen.guardLegal),B=rows.filter(r=>r.frozen.ramLegal),C=rows.filter(r=>r.frozen.guardLegal&&r.frozen.ramLegal),intentSummary={};for(const intent of ['ATTACK','DEFEND','SPECIAL']){const g=rows.filter(r=>r.frozen.enemyIntent===intent);intentSummary[intent]={states:g.length,redlineRiskEvents:g.reduce((n,r)=>n+r.branches.REDLINE.redlineRiskEvent,0),meanRedlineIncoming:g.length?avg(g.map(r=>r.branches.REDLINE),'damageReceived'):0};}let deterministic=true;for(const f of all.slice(0,250))for(const a of ['REDLINE',...(f.guardLegal?['GUARD']:[]),...(f.ramLegal?['RAM']:[])]){const x=runForced(runner,f,a).trace,y=runForced(runner,f,a).trace;if(JSON.stringify(x)!==JSON.stringify(y))deterministic=false;}return {seeds:{start:SEED_START,end:SEED_START+SEED_COUNT-1,count:SEED_COUNT},primarySimulationCount:SEED_COUNT,candidateCounts:{setA:candidates.A.length,setB:candidates.B.length,setC:candidates.C.length,union:all.length},sampled:false,sets:{A:summarize(A),B:summarize(B),C:summarize(C),noSpenderAvailable:rows.filter(r=>r.branches.NO_SPENDER).length},comparisons:{A_Redline_vs_Guard:deltas(A,'REDLINE','GUARD'),A_Redline_vs_NoSpender:deltas(A,'REDLINE','NO_SPENDER'),B_Redline_vs_Ram:deltas(B,'REDLINE','RAM'),B_Redline_vs_NoSpender:deltas(B,'REDLINE','NO_SPENDER'),C_Redline_vs_Guard:deltas(C,'REDLINE','GUARD'),C_Redline_vs_Ram:deltas(C,'REDLINE','RAM'),C_Redline_vs_NoSpender:deltas(C,'REDLINE','NO_SPENDER')},intentSummary,determinism:deterministic,tests:runTests(source),manualCounterfactuals:manualCounterfactuals(),rngMethod:'All branches start from the exact frozen PRNG state; later RNG consumption is branch-native.',stateFreeze:'turn + HPs + Energy + Nitro + intent + hand + draw pile + discard + enemy state + legality + PRNG state.',limitations:['Forced branches replay the exact Phase 6 source through runtime instrumentation; Phase 6 itself is not modified.','Post-action RNG consumption is branch-native when actions consume different numbers of draws.','No-spender is available only when Shot is legal; no artificial pass action is invented.','Manual states are excluded from real-state statistics.']};}
export function runTests(source){const runner=loadInstrumented(source);let candidate=null,seed=100001;for(;seed<SEED_START+SEED_COUNT&&!candidate;seed++){const r=runner.run(seed,'B','adaptive','basic','normal',true);candidate=r.trace.find(t=>t.redlineEligible);if(candidate)candidate={...candidate,seed};}if(!candidate)throw new Error('no test candidate');const f=freezeFromTrace(candidate);for(const a of ['REDLINE',...(f.guardLegal?['GUARD']:[]),...(f.ramLegal?['RAM']:[]),'NO_SPENDER']){if(a==='NO_SPENDER'&&!f.availableActions.includes('shot'))continue;const b=runForced(runner,f,a);if(b.trace.stateKey!==f.stateKey)throw new Error('state freeze mismatch');if(a==='REDLINE'&&b.trace.chosen?.kind!=='redline')throw new Error('forced redline');if(a==='GUARD'&&b.trace.chosen?.kind!=='guardNitro')throw new Error('forced guard');if(a==='RAM'&&(b.trace.chosen?.id!=='ram'||!b.trace.chosen?.ramSpend))throw new Error('forced ram');}if(!Number.isInteger(f.rngState))throw new Error('rng snapshot');const rr=runForced(runner,f,'REDLINE'),gg=f.guardLegal?runForced(runner,f,'GUARD'):null;if(gg&&rr.trace.stateKey!==gg.trace.stateKey)throw new Error('branch initial state mismatch');const expectedPostNitro=rr.trace.chosen?.id==='pump'?Math.min(100,f.nitro-25+35):f.nitro-25;if(rr.trace.post.nitro!==expectedPostNitro)throw new Error('nitro accounting');if(f.enemyHP-rr.trace.post.enemyHp<0)throw new Error('enemy hp accounting');if(rr.trace.post.hp!==f.playerHP)throw new Error('player hp accounting');if(f.energy-rr.trace.post.energy<1)throw new Error('energy accounting');return 'PASS';}
export function loadAndRun(){const here=path.dirname(fileURLToPath(import.meta.url));return runPhase9(fs.readFileSync(path.resolve(here,'../rocket_bunny_phase6/phase6_redline.mjs'),'utf8'));}
if(process.argv[1]&&process.argv[1].endsWith('phase9_forced_choice.mjs'))console.log(JSON.stringify(loadAndRun(),null,2));
